// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"
)

const getPublicProduct = `-- name: GetPublicProduct :one
SELECT p.id, p.slug, p.name, p.category_id, p.status, p.price_rials, p.min_grams, p.step_grams, p.max_grams, p.search_text, p.content, p.updated_at, p.first_published_at, p.restocked_at, coalesce((p.content->>'outOfStock')::boolean,false)::boolean AS out_of_stock FROM products p WHERE (p.slug=$1 OR p.id=$1) AND p.status='published'
`

type GetPublicProductRow struct {
	Product    Product `json:"product"`
	OutOfStock bool    `json:"out_of_stock"`
}

func (q *Queries) GetPublicProduct(ctx context.Context, slug string) (GetPublicProductRow, error) {
	row := q.db.QueryRow(ctx, getPublicProduct, slug)
	var i GetPublicProductRow
	err := row.Scan(
		&i.Product.ID,
		&i.Product.Slug,
		&i.Product.Name,
		&i.Product.CategoryID,
		&i.Product.Status,
		&i.Product.PriceRials,
		&i.Product.MinGrams,
		&i.Product.StepGrams,
		&i.Product.MaxGrams,
		&i.Product.SearchText,
		&i.Product.Content,
		&i.Product.UpdatedAt,
		&i.Product.FirstPublishedAt,
		&i.Product.RestockedAt,
		&i.OutOfStock,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicArticles = `-- name: ListPublicArticles :many
SELECT id, slug, title, status, content, updated_at FROM articles WHERE status='published' ORDER BY updated_at DESC
`

func (q *Queries) ListPublicArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublicArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Content,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
