// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicProduct = `-- name: GetPublicProduct :one
SELECT p.id, p.slug, p.name, p.category_id, p.status, p.price_rials, p.min_grams, p.step_grams, p.max_grams, p.search_text, p.content, p.updated_at, p.first_published_at, coalesce((p.content->>'outOfStock')::boolean,false)::boolean AS out_of_stock FROM products p WHERE (p.slug=$1 OR p.id=$1) AND p.status='published'
`

type GetPublicProductRow struct {
	ID               string             `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	CategoryID       string             `json:"category_id"`
	Status           string             `json:"status"`
	PriceRials       int64              `json:"price_rials"`
	MinGrams         int64              `json:"min_grams"`
	StepGrams        int64              `json:"step_grams"`
	MaxGrams         int64              `json:"max_grams"`
	SearchText       string             `json:"search_text"`
	Content          []byte             `json:"content"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstPublishedAt pgtype.Timestamptz `json:"first_published_at"`
	OutOfStock       bool               `json:"out_of_stock"`
}

func (q *Queries) GetPublicProduct(ctx context.Context, slug string) (GetPublicProductRow, error) {
	row := q.db.QueryRow(ctx, getPublicProduct, slug)
	var i GetPublicProductRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CategoryID,
		&i.Status,
		&i.PriceRials,
		&i.MinGrams,
		&i.StepGrams,
		&i.MaxGrams,
		&i.SearchText,
		&i.Content,
		&i.UpdatedAt,
		&i.FirstPublishedAt,
		&i.OutOfStock,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, description FROM categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicArticles = `-- name: ListPublicArticles :many
SELECT id, slug, title, status, content, updated_at FROM articles WHERE status='published' ORDER BY updated_at DESC
`

func (q *Queries) ListPublicArticles(ctx context.Context) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublicArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Article
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Status,
			&i.Content,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicProducts = `-- name: ListPublicProducts :many
SELECT p.id, p.slug, p.name, p.category_id, p.status, p.price_rials, p.min_grams, p.step_grams, p.max_grams, p.search_text, p.content, p.updated_at, p.first_published_at, coalesce((p.content->>'outOfStock')::boolean,false)::boolean AS out_of_stock FROM products p
WHERE p.status='published' AND ($1::text='' OR p.category_id=$1)
AND ($2::text='' OR p.search_text LIKE '%'||$2||'%' OR similarity(p.search_text,$2)>0.12)
ORDER BY CASE WHEN p.search_text=$2 THEN 0 WHEN p.search_text LIKE $2||'%' THEN 1 ELSE 2 END, similarity(p.search_text,$2) DESC, p.name LIMIT 200
`

type ListPublicProductsParams struct {
	Category string `json:"category"`
	Query    string `json:"query"`
}

type ListPublicProductsRow struct {
	ID               string             `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	CategoryID       string             `json:"category_id"`
	Status           string             `json:"status"`
	PriceRials       int64              `json:"price_rials"`
	MinGrams         int64              `json:"min_grams"`
	StepGrams        int64              `json:"step_grams"`
	MaxGrams         int64              `json:"max_grams"`
	SearchText       string             `json:"search_text"`
	Content          []byte             `json:"content"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstPublishedAt pgtype.Timestamptz `json:"first_published_at"`
	OutOfStock       bool               `json:"out_of_stock"`
}

func (q *Queries) ListPublicProducts(ctx context.Context, arg ListPublicProductsParams) ([]ListPublicProductsRow, error) {
	rows, err := q.db.Query(ctx, listPublicProducts, arg.Category, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublicProductsRow
	for rows.Next() {
		var i ListPublicProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CategoryID,
			&i.Status,
			&i.PriceRials,
			&i.MinGrams,
			&i.StepGrams,
			&i.MaxGrams,
			&i.SearchText,
			&i.Content,
			&i.UpdatedAt,
			&i.FirstPublishedAt,
			&i.OutOfStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
