// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID        string             `json:"id"`
	Slug      string             `json:"slug"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Content   []byte             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Product struct {
	ID               string             `json:"id"`
	Slug             string             `json:"slug"`
	Name             string             `json:"name"`
	CategoryID       string             `json:"category_id"`
	Status           string             `json:"status"`
	PriceRials       int64              `json:"price_rials"`
	MinGrams         int64              `json:"min_grams"`
	StepGrams        int64              `json:"step_grams"`
	MaxGrams         int64              `json:"max_grams"`
	SearchText       string             `json:"search_text"`
	Content          []byte             `json:"content"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstPublishedAt pgtype.Timestamptz `json:"first_published_at"`
	RestockedAt      pgtype.Timestamptz `json:"restocked_at"`
}
