// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	Recipient  string `json:"recipient"`
	Phone      string `json:"phone"`
	Province   string `json:"province"`
	City       string `json:"city"`
	Street     string `json:"street"`
	PostalCode string `json:"postal_code"`
}

type Article struct {
	ID        string             `json:"id"`
	Slug      string             `json:"slug"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Content   []byte             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ArticleDraft struct {
	ArticleID string             `json:"article_id"`
	Content   []byte             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID        int64              `json:"id"`
	StaffID   pgtype.Text        `json:"staff_id"`
	Action    string             `json:"action"`
	EntityID  string             `json:"entity_id"`
	Detail    []byte             `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Cart struct {
	SessionHash string `json:"session_hash"`
	ProductID   string `json:"product_id"`
	Grams       int64  `json:"grams"`
}

type Category struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Inventory struct {
	ProductID     string `json:"product_id"`
	StockGrams    int64  `json:"stock_grams"`
	ReservedGrams int64  `json:"reserved_grams"`
}

type Job struct {
	ID          int64              `json:"id"`
	Kind        string             `json:"kind"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	Attempts    int32              `json:"attempts"`
	AvailableAt pgtype.Timestamptz `json:"available_at"`
}

type Order struct {
	ID                   string             `json:"id"`
	UserID               string             `json:"user_id"`
	IdempotencyKey       string             `json:"idempotency_key"`
	Status               string             `json:"status"`
	Address              []byte             `json:"address"`
	SubtotalRials        int64              `json:"subtotal_rials"`
	ShippingRials        int64              `json:"shipping_rials"`
	TotalRials           int64              `json:"total_rials"`
	ReservationExpiresAt pgtype.Timestamptz `json:"reservation_expires_at"`
	Tracking             string             `json:"tracking"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	OrderID    string `json:"order_id"`
	ProductID  string `json:"product_id"`
	Name       string `json:"name"`
	Grams      int64  `json:"grams"`
	PriceRials int64  `json:"price_rials"`
	TotalRials int64  `json:"total_rials"`
}

type OtpChallenge struct {
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	Attempts  int32              `json:"attempts"`
}

type PaymentAttempt struct {
	ID        string             `json:"id"`
	OrderID   string             `json:"order_id"`
	Status    string             `json:"status"`
	Provider  string             `json:"provider"`
	Reference pgtype.Text        `json:"reference"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID         string             `json:"id"`
	Slug       string             `json:"slug"`
	Name       string             `json:"name"`
	CategoryID string             `json:"category_id"`
	Status     string             `json:"status"`
	PriceRials int64              `json:"price_rials"`
	MinGrams   int64              `json:"min_grams"`
	StepGrams  int64              `json:"step_grams"`
	MaxGrams   int64              `json:"max_grams"`
	SearchText string             `json:"search_text"`
	Content    []byte             `json:"content"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ProductDraft struct {
	ProductID string             `json:"product_id"`
	Content   []byte             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RateLimit struct {
	Key       string             `json:"key"`
	Hits      int32              `json:"hits"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Session struct {
	TokenHash string             `json:"token_hash"`
	Csrf      string             `json:"csrf"`
	UserID    pgtype.Text        `json:"user_id"`
	StaffID   pgtype.Text        `json:"staff_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Setting struct {
	ID             bool  `json:"id"`
	PackagingGrams int64 `json:"packaging_grams"`
}

type ShippingRule struct {
	ID       string `json:"id"`
	Province string `json:"province"`
	MaxGrams int64  `json:"max_grams"`
	FeeRials int64  `json:"fee_rials"`
}

type Staff struct {
	ID           string `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	TotpSecret   string `json:"totp_secret"`
	LastTotpStep int64  `json:"last_totp_step"`
	Role         string `json:"role"`
	Active       bool   `json:"active"`
}

type StockMovement struct {
	ID         int64              `json:"id"`
	ProductID  string             `json:"product_id"`
	DeltaGrams int64              `json:"delta_grams"`
	Reason     string             `json:"reason"`
	OrderID    pgtype.Text        `json:"order_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        string             `json:"id"`
	Phone     string             `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
