import type { components } from "./api-types";
export type Product = components["schemas"]["Product"];
export type Category = components["schemas"]["Category"];
export type Article = components["schemas"]["Article"];
export type Address = components["schemas"]["Address"];
export type Cart = components["schemas"]["Cart"];
export type Order = components["schemas"]["Order"];
export type Session = components["schemas"]["Session"];
export type Quote = components["schemas"]["Quote"];
export type ShippingConfig = components["schemas"]["ShippingConfig"];
export type Member = components["schemas"]["Member"];
